# Generated by Django 5.1.9 on 2025-06-10 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0008_contentprompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('humorous', 'Humorous'), ('promotional', 'Promotional')], default='formal', max_length=50)),
                ('generated_caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentprompts_contentgen', to='scheduler.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentprompts_contentgen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
