# Generated by Django 5.2.1 on 2025-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_post_created_at_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
