# Generated by Django 5.2.1 on 2025-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_platform_added_by_platform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
