# Generated by Django 5.2.1 on 2025-06-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_platform_expires_in_platform_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='refresh_token',
        ),
    ]
