# Generated by Django 5.2.1 on 2025-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_platform_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
