# Generated by Django 5.1.9 on 2025-06-10 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_platform_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('generated_caption', models.TextField()),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('humorous', 'Humorous'), ('promotional', 'Promotional'), ('informative', 'Informative')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentprompts_scheduler', to='scheduler.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentprompts_scheduler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
