# Generated by Django 5.1.9 on 2025-06-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
    ]
