# Generated by Django 5.1.9 on 2025-06-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generated_caption_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='generated_image_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AIGeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('caption', 'Caption')], max_length=10)),
                ('source_model', models.CharField(max_length=100)),
                ('generation_prompt', models.TextField()),
                ('output_data', models.TextField(help_text='Base64 string or image URL')),
                ('file', models.ImageField(blank=True, null=True, upload_to='ai_generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assets', to='scheduler.post')),
            ],
        ),
    ]
